---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: America/New_York
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "ScottyMJacobson"
keywords:    "web developer, full-stack, musician, designer, programmer, coder, hacker"
description: "Homepage for NYC-based web developer, musician, and all-around hacker."
source_link: "https://github.com/ScottyMJacobson/ScottyMJacobson.github.io"
favicon:     "icons/favicon.ico"
touch_icon:  "icons/apple-icon.png"
google_analytics_key: UA-66673802-1


# Site owner
owner: 
  name: Scotty M Jacobson
  email: ScottyMJacobson@gmail.com
  twitter: ScottyMJacobson
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: img/headshot.jpeg # 160x160 px image for author byline



kramdown:
  auto_ids:  false

